name: SUSC-craft
version: '${version}'
main: susc.s01.SUSC_craft
api-version: '1.20'

commands:
  ExportingPlayerJoinLog:
    description: PlayerJoinLog 가 Exporting 됩니다.
  CheckPlayerJoinLog:
    description: PlayerJoinLog 리스트에서 특정 플레이어 데이터를 확인합니다.
